### ISSUE TITLE
Ability to cleanup only closed comments

### ISSUE THREAD

**Issue by Kleeven81** [AgileReview-Project/AgileReview-Legacy-Plugin#13]
We would like the ability to do a cleanup that only removes the closed comments. This way we can remove all closed review items and keep those that still need attention.

**Comment by may-bee** [comment]
Interesting feature.
I (or at least we) will have a look at this soon.

**Comment by postmann** [comment]
@Kleeven81: Thanks a lot for your interest in AgileReview and your feedback. Searching for comments with status "closed" is already possible. You can then simply remove them by selecting all comments and clicking the remove button in the Comments Summary View. Does this option suffice your needs?

![auswahl_001](https://cloud.githubusercontent.com/assets/490898/6426519/945f2ea6-bf5f-11e4-8d2d-cc01a1fb0216.png)

Still, I thought about this feature request for a while. The current way to do this might not be the best one (regarding UX). I think extending the cleanup option might not be the best idea as well. I would really like to keep the cleanup a one-click option without too many options to select from. Instead, an option would be to extend the Comments Summary View a bit. This view already has the option to "only show open comments".
This is actually the inverse option of what Kleeven81 request. Adding and additional filter "only show closed comments" would allow users to select those comments that are in state closed with one click instead of having to filter for those comments.

**Comment by Kleeven81** [comment]
This was what I used in the end. It is definitely usable. I was hoping for an easy one click alternative to make it easier/faster.

Maybe it can be helpful if users can override the standard cleanup option to only remove closed comments. That way only the users that want this behaviour can use it and others will still have the standard cleanup functionality.

As I'm just a single user requesting this, if you don't see any added value in this feature I'll just keep doing it the 'old' way.

**Comment by postmann** [comment]
In our project, the needs of the many do not outweight the needs of the few (if their feature requests are reasonable) ;) 

I'll check what it would take to extend the cleanup option and will come up with some proposal.

**Comment by postmann** [comment]
It's been a while since I promised a proposal but good things come to those who wait ;)

Here's my idea of an improved Cleanup Action. I moved the configuration options to the preferences page instead of asking the user each time whether he wants to keep the comments. In addition, I created a new option to ignore open comments.
![preferences](https://cloud.githubusercontent.com/assets/490898/6981238/5463332e-d9fe-11e4-9789-655454f5ac03.png)

Now, during cleanup the user is asked if he really wants to perform the cleanup and is informed about the current configuration.
![cleanup_dialog](https://cloud.githubusercontent.com/assets/490898/6981239/5464795a-d9fe-11e4-8fd1-44445ba3c225.png)

@Kleeven81: does this suit your needs? Its not available via the development update site yet, but I think the screenshots give a good impression of the modifications I made.

**Comment by Kleeven81** [comment]
That looks like it will suit our needs perfectly!

**Comment by postmann** [comment]
Approved by user and fellow developers. Closing. Will be merged into development branch soon.

**Comment by thebold** [comment]
This ability was only solved for the project cleanup and not for the cleanup in the review explorer. The same functionality should also existing in the review explorer.
